CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  "fullName" TEXT,
  role TEXT
);

CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  stock INT DEFAULT 0,
  "buyPrice" NUMERIC DEFAULT 0,
  "sellPrice" NUMERIC DEFAULT 0,
  unit TEXT
);

CREATE TABLE barang_masuk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transactionId" TEXT UNIQUE NOT NULL,
  "itemCode" TEXT NOT NULL,
  "itemName" TEXT,
  supplier TEXT,
  quantity INT DEFAULT 0,
  date TEXT
);

CREATE TABLE barang_keluar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transactionId" TEXT UNIQUE NOT NULL,
  "itemCode" TEXT NOT NULL,
  "itemName" TEXT,
  quantity INT DEFAULT 0,
  date TEXT
);

CREATE TABLE supplier (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplierId" TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT
);

CREATE TABLE kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kategoriId" TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL
);

-- Insert default admin user
INSERT INTO users (username, password, "fullName", role)
VALUES ('admin', 'admin123', 'Administrator', 'Admin'),
       ('manager', 'manager123', 'Manager', 'Manajemen');
